pipeline:
  identifier: Build_shubhamchav_SmpleJavaTest_1737366015057
  name: Build SmpleJavaTest
  orgIdentifier: default
  projectIdentifier: default_project
  properties:
    ci:
      codebase:
        build: <+input>
        connectorRef: account.Github
        repoName: shubhamchav/SmpleJavaTest
  stages:
    - stage:
        identifier: build
        name: build
        spec:
          caching:
            enabled: true
          cloneCodebase: true
          execution:
            steps:
              - step:
                  type: Run
                  name: Build
                  identifier: Build
                  spec:
                    shell: Sh
                    command: mvn clean install
              - step:
                  type: Test
                  name: Test
                  identifier: Test
                  spec:
                    shell: Sh
                    command: mvn test
                    intelligenceMode: true
              - step:
                  type: Run
                  name: Package
                  identifier: Package
                  spec:
                    shell: Sh
                    command: mvn package
          platform:
            os: Linux
            arch: Amd64
          runtime:
            type: Cloud
            spec: {}
        type: CI
